src/Web/Controllers/BibliotecaController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using UsuarioBiblioteca.Application.Interfaces;

namespace Web.Controllers
{
    public class BibliotecaController : Controller
    {
        private readonly IBibliotecaria _bibliotecaria;
        private readonly IEndereco _endereco;
        private readonly ILivro _livro; 
        private readonly List<string> erros = new List<string>();
        private readonly Biblioteca.Core.Domain.Foto.HelperFoto _foto = new Biblioteca.Core.Domain.Foto.HelperFoto();
        private readonly Biblioteca.Core.Domain.Util.RegistrarDados _registrar = new Biblioteca.Core.Domain.Util.RegistrarDados();
        private readonly Biblioteca.Core.Domain.Util.RetornarDados _retornar = new Biblioteca.Core.Domain.Util.RetornarDados();

        private readonly string retorno = string.Empty;

        public BibliotecaController(IBibliotecaria bibli, IEndereco en,ILivro lv)
        {
            _bibliotecaria = bibli;
            _endereco = en;
            _livro = lv;

        }
        // GET: Biblioteca
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastro()
        {
            var model = new UsuarioBiblioteca.Application.ViewModel.Bibliotecaria();
            model._liststatus = model.ListStatus();
            return View(model);
        }
        [HttpPost]
        public ActionResult RespostaCadastro(FormCollection model) {
            var _biblio = new UsuarioBiblioteca.Application.ViewModel.Bibliotecaria() {
                RazaoSocial = model["RazaoSocial"],
                Cnpj = model["cnpj"],
                Email = model["email"],
                Usuario = model["Usuario"],
                Imagem = Request.Files["Imagem"].FileName,
                Senha = model["Senha"],
                ConfirmaSenha = model["ConfirmaSenha"]
            };
            List<UsuarioBiblioteca.Application.ViewModel.Bibliotecaria> b = new List<UsuarioBiblioteca.Application.ViewModel.Bibliotecaria>
            {
                _biblio
            };
            _foto.ArquivarFoto(Request.Files["Imagem"]);
            TempData["BiblioDados"] = b;
            TempData["token"] = model["token"];
            return Json(new { Msg = "Dados enviados" }, JsonRequestBehavior.AllowGet);
        
        
    }

        public ActionResult Endereco()
        {
            var model = new UsuarioBiblioteca.Application.ViewModel.Endereco();
            model._listp = model.ListTipos();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Endereco(UsuarioBiblioteca.Application.ViewModel.Endereco end) {
            if (ModelState.IsValid) {
                TempData.Keep("BiblioDados");
                TempData.Keep("token");
                string token = TempData["token"].ToString();
                var biblioteca = (List<UsuarioBiblioteca.Application.ViewModel.Bibliotecaria>)TempData["BiblioDados"];
                foreach (var _bi in biblioteca)
                {
                    var b = new UsuarioBiblioteca.Application.ViewModel.Bibliotecaria()
                    {
                        Id = Guid.NewGuid(),
                        Cnpj = _bi.Cnpj,
                        Senha = _bi.Senha,
                        ConfirmaSenha = _bi.ConfirmaSenha,
                        Email = _bi.Email,
                        RazaoSocial = _bi.RazaoSocial,
                        Situacao = _bi.Situacao,
                        Imagem = _bi.Imagem,
                        Usuario = _bi.Usuario

                    };
                  
                    try
                    {
                        var retorno = _registrar.PostDados<UsuarioBiblioteca.Application.ViewModel.Bibliotecaria>(System.Configuration.ConfigurationManager.AppSettings["urlweb"] + "biblioteca/Gestao/registrar-biblioteca", token, b);
                        if (retorno.Result.ListaErros.Count > 0)
                        {
                            foreach (var erro in retorno.Result.ListaErros)
                                erros.Add(erro);
                            ViewBag.Msg = erros;
                        }
                        else
                        {
                            end.Bibliotecaria.Id = retorno.Result.Id;
                            var x = _registrar.PostDados<UsuarioBiblioteca.Application.ViewModel.Endereco>(System.Configuration.ConfigurationManager.AppSettings["urlweb"] + "biblioteca/Gestao/registrar-endereco", token, end);
                            erros.Add("Dados enviados com sucesso");
                            ViewBag.Msg = erros;

                        }
                        var model = new UsuarioBiblioteca.Application.ViewModel.Endereco();
                        model._listp = model.ListTipos();
                         
                        return View(model);

                    }
                    catch (Exception e)
                    {

                        throw new Exception(e.Message);
                    }
                }

            }
                return View();
        }

        public ActionResult Livro() {
           //chamar a api de
            var model = new UsuarioBiblioteca.Application.ViewModel.Livro();
            ViewBag.tokenlivro = string.Empty;

            model._listlv = model.ListCategoria();
            model.ListBiblioteca = _livro.DropBiblioteca(); 
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Livro(FormCollection form) {

            try
            {
                UsuarioBiblioteca.Application.ViewModel.Livro model = null;

                if (ModelState.IsValid)
                {
                    var livro = new UsuarioBiblioteca.Application.ViewModel.Livro()
                    {
                        Ativo = true,
                        IdBiblioteca = Guid.Parse(form["IdBiblioteca"]),
                        Titulo = form["Titulo"],
                        Descricao = form["Descricao"],
                        Editora = form["Editora"],
                        QtdPg = Convert.ToInt32(form["QtdPg"]),
                        DescCategoria = form["DescCategoria"],
                        Id = Guid.NewGuid()


                    };
                    var retorno = _registrar.PostDados<UsuarioBiblioteca.Application.ViewModel.Livro>(System.Configuration.ConfigurationManager.AppSettings["urlweb"] + "Livro/Gestao/registrar-livro", form["tokenlivro"], livro);
                    if (retorno.Result.ListaErros.Count > 0)
                    {

                        foreach (var erro in retorno.Result.ListaErros)
                            erros.Add(erro);
                        ViewBag.Msg = erros;
                    }

                    model = new UsuarioBiblioteca.Application.ViewModel.Livro();
                    model._listlv = model.ListCategoria();
                    model.ListBiblioteca = _livro.DropBiblioteca();
               
                }
                return View(model);

            }
            catch (Exception e)
            {

                throw new Exception(e.Message);
            }
           
        }

        public ActionResult Lista() {
            return View();
        }

        public ActionResult EditarLivro(Guid idlivro) {
            return View();
        }
        

        
    }       


}

src/Web/Controllers/LoginBibliotecaController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using UsuarioBiblioteca.Application.Interfaces;

namespace Web.Controllers
{
    public class LoginBibliotecaController : Controller
    {
     
        private readonly IAdministrador _admin;
        private List<string> erros = new List<string>();
        public LoginBibliotecaController(IAdministrador adm)
        {
            _admin = adm;
        }
        // GET: LoginBiblioteca
        public ActionResult Index()
        {
            ViewBag.TitlePag = "Administrador";
            return View();
        }

        public ActionResult CadAdministrador()
        {
            ViewBag.TitlePag = "Administrador";
            return View();

        }

      
        public ActionResult RespostaAdm(FormCollection model)
        {
            try
            {
                var adm = new UsuarioBiblioteca.Application.ViewModel.Administrador()
                {
                    Nome = model["Nome"],
                    Email = model["Email"],
                    Senha = model["Senha"],
                    ConfirmaSenha = model["ConfirmaSenha"],
                    Login = model["Login"]
                };
                _admin.Adicionar(adm);

                if (adm.ListaErros.Count > 0)
                {
                    adm.ListaErros.ForEach(x => erros.Add(x));
                    
                    return Json(new { Msg = erros }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { Msg = "Dados Cadastrado com sucesso" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception f)
            {

                return Json(new { Msg = f.Message }, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult RecuperarSenha()
        {
            ViewBag.TitlePag = "Administrador";
            return View();
        }

       

        public ActionResult RedefinirSenha()
        {
            ViewBag.TitlePag = "Administrador";
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult RedefinirSenha(UsuarioBiblioteca.Application.ViewModel.Administrador adm)
        {
            if (ModelState.IsValid) { }
            return View();
        }

    }
}

src/Web/Views/LoginBiblioteca/CadAdministrador.cshtml
@{
    ViewBag.Title = "Cadastro de Administrador";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
@model UsuarioBiblioteca.Application.ViewModel.Administrador
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery/jquery-mask.js"></script>


<div class="container text-center">


    @using (Html.BeginForm("", "", FormMethod.Post, new { @name = "FormCadastro", @ng_controller = "authctrladm", @class = "form-login", @novalidate = "novalidate" }))
    {
        <span style="text-align: center" class="text-danger">{{MsgRetorno}}</span>
        @Html.AntiForgeryToken()

        <div class="form-group">

            @Html.TextBoxFor(c => c.Nome, new { @type = "text", @class = "form-control", @placeholder = "Seu nome", @name = "Nome", @ng_model = "Nome", @ng_required = "true" })
            <span style="color:red" ng-show="FormCadastro.Nome.$dirty && FormCadastro.Nome.$invalid && FormCadastro.Nome.$error.required">
                Nome é obrigatório.
            </span>
        </div>

        <div class="form-group">

            @Html.TextBoxFor(c => c.Login, new { @type = "text", @class = "form-control", @placeholder = "Seu Usuario", @name = "Login", @ng_model = "Login", @ng_required = "true" })
            <span style="color:red" ng-show="FormCadastro.Login.$dirty && FormCadastro.Login.$invalid && FormCadastro.Login.$error.required">
                Login é obrigatório.
            </span>
        </div>
        <div class="form-group">

            @Html.TextBoxFor(c => c.Senha, new { @type = "password", @class = "form-control", @placeholder = "Sua senha", @name = "Senha", @ng_model = "Senha", @ng_required = "true", @ng_maxlength = "6", @ng_minlength = "6" })
            <span style="color:red" ng-show="FormCadastro.Senha.$dirty && FormCadastro.Senha.$invalid && FormCadastro.Senha.$error.required">
                Senha é obrigatório.
            </span>
            <span style="color:red" ng-show="FormCadastro.Senha.$error.maxlength || FormCadastro.Senha.$error.minlength">
                Senha deve ter 6 caracteres
            </span>
        </div>
        <div class="form-group">

            @Html.TextBoxFor(c => c.ConfirmaSenha, new { @type = "password", @class = "form-control", @placeholder = "Confirmar senha", @name = "ConfirmaSenha", @ng_model = "ConfirmaSenha", @ng_required = "true", @ng_maxlength = "6", @ng_minlength = "6" })
            <span style="color:red" ng-show="FormCadastro.ConfirmaSenha.$dirty && FormCadastro.ConfirmaSenha.$invalid && FormCadastro.ConfirmaSenha.$error.required">
                Confir.Senha é obrigatório.
            </span>
            <span style="color:red" ng-show="FormCadastro.ConfirmaSenha.$error.maxlength || FormCadastro.ConfirmaSenha.$error.minlength">
                Senha deve ter 6 caracteres
            </span><br />
            <span style="color:red" ng-if="Senha != ConfirmaSenha">
                Senha divergente
            </span>
        </div>

        <div class="form-group">

            @Html.TextBoxFor(c => c.Email, new { @type = "email", @class = "form-control", @placeholder = "Sua Email", @name = "Email", @ng_model = "Email", @ng_required = "true" })
            <span style="color:red" ng-show="FormCadastro.Email.$dirty && FormCadastro.Email.$invalid && FormCadastro.Email.$error.required">
                Email é obrigatório.
            </span>
            <span style="color:red" ng-show="FormCadastro.Email.$error.email">
                Email inválido.
            </span>
        </div>
        <div class="form-group">

            @Html.TextBoxFor(c => c.ConfirmEmail, new { @type = "email", @class = "form-control", @placeholder = "Confirmação do Email", @name = "ConfirmEmail", @ng_model = "ConfirmEmail", @ng_required = "true" })
            <span style="color:red" ng-show="FormCadastro.v.$dirty && FormCadastro.ConfirmEmail.$invalid && FormCadastro.ConfirmEmail.$error.required">
                Confir.Email é obrigatório.
            </span>
            <span style="color:red" ng-show="FormCadastro.v.$error.email">
                Email inválido.
            </span>
            <span style="color:red" ng-if="Email != ConfirmEmail">
                E-mail divergente
            </span>
        </div>



        <div class="form-group">
            <button type="button" id="btnbotao" class="btn btn-xg btn_verde"
                    ng-disabled="FormCadastro.Nome.$invalid ||
                    FormCadastro.Login.$invalid ||
                    FormCadastro.Senha.$invalid ||
                    FormCadastro.ConfirmaSenha.$invalid || FormCadastro.Email.$invalid ||
                            FormCadastro.ConfirmEmail.$invalid" ng-click="RegistrarAdm()">
                Salvar
            </button>
        </div>
    }

</div>

src/Web/Views/LoginBiblioteca/Index.cshtml
@{
    ViewBag.Title = "Adm  - Biblioteca";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
@model UsuarioBiblioteca.Application.ViewModel.Administrador

<div class="container text-center">


    @using (Html.BeginForm("Index", "Biblioteca", FormMethod.Post, new { @id = "FormLogin", ng_controller = "authctrladm", @class = "form-login" }))
    {
        @Html.AntiForgeryToken()
        @*if (string.IsNullOrEmpty(TempData["msgSucesso"].ToString()))
        { <span style="text-align: center" class="text-danger">@TempData["msgSucesso"]</span>}*@  
    <span style="text-align: center" class="text-danger">{{MsgRetorno}}</span><br />
    <div class="form-group">
        @Html.TextBoxFor(c => c.Login, new { @type = "text", ng_model = "Login", @class = "form-control", @placeholder = "Seu Email" })
    </div>
    <div class="form-group">
        @Html.TextBoxFor(c => c.Senha, new { @type = "password", ng_model = "Senha", @class = "form-control", @placeholder = "Sua senha" })
    </div>
    <div class="form-group">
        <button type="button" id="btnbotao" class="btn btn-xg btn_verde" ng-click="ProcessarBotao('btnbotao','Aguarde a Verificação');">Acessar</button>
    </div>
}
    <div class="text-center">
        <a class="d-block small mt-3" href="@Url.Action("CadAdministrador","LoginBiblioteca")">Criar sua Conta</a>
        <a class="d-block small" href="@Url.Action("RecuperarSenha","LoginBiblioteca")">Esqueçeu sua senha?</a>
    </div>
</div>

src/Web/Views/LoginBiblioteca/RecuperarSenha.cshtml
@{
    ViewBag.Title = "Recuperar Senha";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

@model UsuarioBiblioteca.Application.ViewModel.Administrador

<div class="container">
    <div class="card card-login mx-auto mt-5">
        <div class="card-header">Recuperar Senha</div>
        <div class="card-body">

            @using (Html.BeginForm("RecuperarSenha", "LoginBiblioteca", FormMethod.Post, new { @id = "FormRecuperar", @ng_controller = "authctrl" }))
            {
                @Html.AntiForgeryToken()
                if (TempData["msgSucesso"] != null)
                { <span style="text-align: center" class="text-danger">@TempData["msgSucesso"]</span>}

            <div class="form-group">
                @Html.Label("Email")
                @Html.TextBoxFor(c => c.Email, new { @type = "email", @class = "form-control", @placeholder = "Sua Email", @ng_model = "FormRecuperar.Email" })
            </div>
            <div class="form-group">
                <input type="submit" value="Recuperar" class="btn-dark" />
            </div>
        }
        </div>
    </div>
</div>

src/Web/Views/LoginBiblioteca/RedefinirSenha.cshtml
@{
    ViewBag.Title = "Redefinir Senha";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

@model UsuarioBiblioteca.Application.ViewModel.Administrador

<div class="container">
    <div class="card card-login mx-auto mt-5">
        <div class="card-header">Redefinição de Senha de Acesso</div>
        <div class="card-body">

            @using (Html.BeginForm("RedefinirSenha", "LoginBiblioteca", FormMethod.Post, new { @id = "FormCadastro", @ng_controller = "authctrl" }))
            {
                <span style="text-align: center">@Html.ValidationMessageFor(m => m.Error)</span>
                @Html.AntiForgeryToken()
                if (TempData["msgSucesso"] != null)
                { <span style="text-align: center" class="text-danger">@TempData["msgSucesso"]</span>}

                  <div class="form-group">
                      @Html.LabelFor(model => model.Email)
                      @Html.TextBoxFor(c => c.Email, new { @type = "email", @class = "form-control", @placeholder = "Sua Email" })
                  </div>

            <div class="form-group">
                @Html.LabelFor(model=>model.Senha)
                @Html.TextBoxFor(c => c.Senha, new { @type = "password", @class = "form-control", @placeholder = "Sua senha" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmaSenha)
                @Html.TextBoxFor(c => c.ConfirmaSenha, new { @type = "password", @class = "form-control", @placeholder = "Confirma senha" })
            </div>
            <div class="form-group">
                <input type="submit" value="Redefinir" class="btn-dark" />
            </div>
        }
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>